name: vib-acc
dependencies:
- python 
- numpy
- pytest
- pytest-cov
- flake8
- scipy
- pandas
- jupyter
- spyder==4.2.5
- matplotlib
- shapely
- pip
- pip:
  - pylife
  - spyder-unittest
  - torch
  - pytorch-lightning
  - trimesh